### ISSUE TITLE
Is project still alive and if so, can this be fixed?

### ISSUE THREAD

**Issue by hazendaz** [OWASP/json-sanitizer#10]
There haven't been any commits for a long time so not sure if this is still alive.  If it is, the JSR305 needs to be phsyically defined to a version instead of attempting to look for newer version.  That look is bad practace and it does cause occassional failures due to network issues.  I'm more than willing to fix it as it rarely ever changes but wanted to find out if this project is still alive as I'd want to do a lot of maven cleanup on top of that and get a release soon.

**Comment by jmanico** [comment]
Jeremy,

Any help you care to provide to this project is greatly appreciated and
will be utilized.

Aloha, Jim

**Comment by hazendaz** [comment]
@jmanico Awesome!  I'm going to send what seems like a large pull request (ie lots of commits) but they are broken into pieces really well and documented.  By all means comment on that for what is liked or not liked and I certainly can slim it down.  Initially, everything I'm doing is build related only without any code changes.
