### ISSUE TITLE
pound symbol  is eliminating the closing brackets

### ISSUE THREAD

**Issue by baswashekarbattula** [OWASP/json-sanitizer#13]
I have response object with a description field. when there is a pound symbol in the description, its eliminating the equal number of characters from the  response ending. Due to this closing curly braces are being removed, thus causing distorted json structure.
 This is happening when we are using json-sanitizer 1.1 jar. 

Any suggestions to avoid this?

**Comment by mikesamuel** [comment]
Do you have a testcase?
I tried this but it seems to work fine

```java
    assertSanitized(
        "[ { \"description\": \"aa##############aa\" }, 1 ]",
        "[ { \"description\": \"aa##############aa\" }, 1 ]");```
