### ISSUE TITLE
Should the reserved keywords expand for JDK8 or later?

### ISSUE THREAD

**Issue by harkue** [OWASP/json-sanitizer#24]
JDK8 or later version has more keywords like 'try-with-resources', 'goto', 'volatile'.

```java
private static final String[][] RESERVED_KEYWORDS = {
    {},
    {},
    {"do", "if", "in", },
    {"for", "let", "new", "try", "var"},
    {"case", "else", "enum", "eval", "null", "this", "true", "void", "with"},
    {"catch", "class", "const", "false", "super", "throw", "while", "yield"},
    {"delete", "export", "import", "return", "switch", "static", "typeof"},
    {"default", "extends", "public", "private"},
    {"continue", "function"},
    {"arguments"},
    {"implements", "instanceof"}
  };
```

Reference:  [JDK 8 keywords] (https://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html)

**Comment by mikesamuel** [comment]
try-with-resources just uses `try` followed by a parenthetical, no?  `goto` and `volatile` were keywords from Oak days, no?

Besides, these are javascript reserved keywords.  I think you're right that the list needs some additions: `async` for example.
