### ISSUE TITLE
Sanitizer not removing <script> from input

### ISSUE THREAD

**Issue by urikjaro** [OWASP/json-sanitizer#27]
Hi guys,

the readme page mentions that all <script> tags should be removed from the input JSON, but this does not happen in my test:

My input is following json `{"name":"Fotofeld","data":{"fieldName":"<script>alert(1);</script>"}}`
which gets converted into `{"name":"Fotofeld","data":{"fieldName":"\u003cscript>alert(1);\u003c/script>"}}`, which in my case gets saved to database, and then when I return the "fieldName", the value is back as if without the sanitization..
The problem is that the result of the sanitization gets tagged by the OWASP ZAP..
Screenshot from debugger included
![Screenshot from 2021-02-15 17-37-48](https://user-images.githubusercontent.com/5805858/107973655-c46a5a00-6fb5-11eb-8721-1824dfa4614f.png)

**Comment by mikesamuel** [comment]
We do not remove script tags.  There's no way for the sanitizer to know which properties are strings of HTML.

Might you be thinking of our [Output](https://github.com/OWASP/json-sanitizer#output) guarantees which include?:

> The output will not contain the substrings (case-insensitively) "`<script`", "`</script`" or "`<!--`" and can thus be embedded inside an HTML script element without further encoding.

There's no removal.  Only escaping.

If you need to remove HTML, use an HTML sanitizer like [owasp/java-html-sanitizer](https://github.com/OWASP/java-html-sanitizer) on the value of properties that contain HTML from unknown/untrusted sources.

**Comment by urikjaro** [comment]
Yes, that is what I was reffering to - I thought that they would be remover.
OK, then I will have a look at the html-sanitizer.
Thanks for the link
