### ISSUE TITLE
sanitizer strips part of the value when the value contains a forward slash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OWASP/json-sanitizer#4]
```
What steps will reproduce the problem?
1.add following line to JsonSanitizerTest: assertSanitized("dev/comment", 
"dev/comment");
2.run the test


What is the expected output? What do you see instead?
Instead of the expected output "dev/comment", we get "dev". 

What version of the product are you using? On what operating system?
latest git version, Windows 7


```

Original issue reported on code.google.com by `davidcyp...@gmail.com` on 30 Jan 2015 at 10:14

**Comment by mikesamuel** [comment]
https://github.com/OWASP/json-sanitizer/commit/9227e9d355c3796aaa5c9dc08080a6f90e441217 should address this.

**Comment by jmanico** [comment]
Any comments from the submitters if this is an acceptable patch?

**Comment by timv2** [comment]
Hello,
the patch is working for my case!
Thx imransaeed

**Comment by timv2** [comment]
Hi, 
regarding this issue,

I see the pom is updated to 1.2-SNAPSHOT. However I don't see a release of 1.1. 
In the repository, I can only find 1.1-SNAPSHOT: https://oss.sonatype.org/#nexus-search;quick~mikesamuel
Is there an actual release of 1.1 coming up?

Thx

**Comment by mikesamuel** [comment]
I'm working to get https://github.com/OWASP/json-sanitizer/releases/tag/json-sanitizer-1.1 in maven.

**Comment by mikesamuel** [comment]
Version 1.1 is available : http://search.maven.org/#search%7Cga%7C1%7Cjson-sanitizer
